#!/usr/bin/env php
<?php

require(__DIR__ . '/vendor/autoload.php');

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

defined('YII_DEBUG') or define('YII_DEBUG', get_env('YII_DEBUG', false));
defined('YII_ENV') or define('YII_ENV', get_env('YII_ENV', 'prod'));

require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require __DIR__ . '/config/main.php';
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
